language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 

script:
- npm run build

after_script:
  - ssh root@139.196.51.218 'cd /usr/local/syb/syb-life-cms/ && git pull && npm install && npm run build'
branches:
  only:
  - master