language: node_js
node_js:
- 12.16.2
cache:
  directories:
  - node_modules
install:
- yarn
before_script: 

script:
- yarn build

after_script:
  - ssh root@139.196.51.218 'cd /usr/local/syb/syb-life-cms/ && git pull && yarn && yarn build'
branches:
  only:
  - master